### ISSUE TITLE
Enhancements tracker

### ISSUE THREAD

**Issue by FongYuan** [CS2103-AY1819S1-F10-2/main#107]
This issue is to track the enhancements that everyone is doing.
- [x] Weineng: Password verification
- [x] David: LoanStatus enum, `return`, `summary`
- [x] FY: Bicycle Management
- [x] Irham: Loan ID, `reset` functionalities
- [x] Xiaohang: Censor private info in UI, send reminder email

Peer testing will be in v1.3 so let's try to complete the basic functionality of our enhancements by then.

**Comment by prokarius** [comment]
David:

- [x] `LoanStatus` enum
- [ ] `return` functionality
- [ ] `summary` functionality
