### ISSUE TITLE
Add authentication for deletion of loans

### ISSUE THREAD

**Issue by wn96** [CS2103-AY1819S1-F10-2/main#40]
- [x] Allow setting of password
- [x] Allow changing of password
- [x] Encrypt password in preference.json

**Comment by wn96** [comment]
- [ ] Allow setting of password
- [ ] Allow changing of password
- [ ] Allow adding of password
- [ ] Allow removal of password requirement
- [ ] Delay in asking for password again after password has been typed for X minutes. To add in "settings"

**Comment by wn96** [comment]
[Setting up of bCrypt](https://gist.github.com/craSH/5217757)
