### ISSUE TITLE
I can automatically charge a customer money

### ISSUE THREAD

**Issue by FongYuan** [CS2103-AY1819S1-F10-2/main#59]
- When a loan is returned, display a receipt stating how much money they need to pay for the bike.
- Optionally, implement a simple command to confirm that payment has been made, so that the app goes back to normal operation.

**Comment by prokarius** [comment]
This will include implementing the `return` command.

**Comment by prokarius** [comment]
- [ ] Create LoanStatus enum
- [ ] Ensure status are saved upon closing the application
- [ ] Create `return` method

**Comment by prokarius** [comment]
The first 2 tasks have been implemented in #133

**Comment by prokarius** [comment]
Fixed in #159
